# Docker build and push
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Build
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'node-demo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

# Test
# ...

# Push
- task: Docker@2
  inputs:
    containerRegistry: 'acr' 
    repository: 'node-demo'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest

# Deploy
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: './deployment.yaml'
    secretType: 'dockerRegistry'
    secretName: 'demo-registry'
