# Docker build and push
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Build
steps:
- task: Docker@2
  inputs:
    containerRegistry: 'demo-registry-connection'
    repository: 'node-demo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest

# Test
# ...

# Push
- task: Docker@2
  inputs:
    containerRegistry: 'demo-registry-connection'
    repository: 'node-demo'
    command: 'push'
    tags: |
      $(Build.BuildId)
      latest

# Deploy
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'demo-azure-connection'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: './deployment.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Microsoft Azure Sponsorship (d09f4363-eae7-4c79-864e-08154540c083)'
    azureContainerRegistry: 'boxboatdemo.azurecr.io'
    secretName: 'demo-registry'
    forceUpdate: true