---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
    service: demo
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: http
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-v1
  labels:
    app: demo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
      version: v1
  template:
    metadata:
      labels:
        app: demo
        version: v1
    spec:
      serviceAccountName: demo-sa
      containers:
      - name: demo
        image: boxboatdemo.azurecr.io/node-demo:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      imagePullSecret: demo-registry
---
